### ISSUE TITLE
How to build / run / install

### ISSUE THREAD

**Issue by janosgyerik** [skiwi2/OLog#1]
It would be great to add to the README how to get started hacking and contributing, such as:
- [x] how to build the project
- [x] how to run it (make it do something)
- [x] how to install (if applicable)
- [x] how to run the unit tests (if any)
- [x] how to contribute

**Comment by ShipsWithCannons** [comment]
I agree this is very important. Not just for the project itself but also to keep people interested in what we're doing.

Since all parts are rapidly evolving at the moment the README will change as well. But that's no reason not to write it. Thanks for writing down a list of valuable chapters that should be in said README.

**Comment by janosgyerik** [comment]
Mostly good to go!

- [x] how to build the project
- [x] how to run it (make it do something)
- [x] how to install (if applicable)
- [ ] how to run the unit tests (if any)
- [x] how to contribute
